version: '3.8'

services:
  postgres:
    image: pgvector/pgvector:pg15
    container_name: aci_postgres
    environment:
      POSTGRES_DB: aci_memory
      POSTGRES_USER: aci_user
      POSTGRES_PASSWORD: aci_password
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - aci_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U aci_user -d aci_memory"]
      interval: 30s
      timeout: 10s
      retries: 3

  redis:
    image: redis:7-alpine
    container_name: aci_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - aci_network
    restart: unless-stopped
    command: redis-server --appendonly yes

volumes:
  postgres_data:
  redis_data:

networks:
  aci_network:
    driver: bridge
